version: "3.7"

services:

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/project
      - ./config/nginx:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
    links:
      - php-fpm

  php-fpm:
    build:
      context: php-fpm
    ports:
      - 9000:9000
    volumes:
      - ./src:/var/www/project
    links:
      - db

  db:
    hostname: clickhouse
    image: clickhouse/clickhouse-server:latest
    ports:
      - 8123:8123
    volumes:
      - ./databases/clickhouse:/var/lib/clickhouse
