version: "3.7"

services:

  nginx:
    image: nginx:latest
    ports:
    - 127.0.0.1:80:80
    volumes:
    - ./src:/var/www/project
    - ./config/nginx:/etc/nginx/conf.d
    - ./logs/nginx:/var/log/nginx
    links:
    - php-fpm

  php-fpm:
    build:
      context: php-fpm
    ports:
    - 127.0.0.1:9000:9000
    volumes:
    - ./src:/var/www/project
    links:
    - db

  db:
    image: clickhouse/clickhouse-server:latest
    ports:
    - 127.0.0.1:8123:8123
    restart: always
    volumes:
    - ./databases/clickhouse:/opt/clickhouse/data
